https://docs.djangoproject.com/el/2.2/
https://docs.djangoproject.com/es/2.2/
https://docs.djangoproject.com/fr/2.2/
https://docs.djangoproject.com/id/2.2/
https://docs.djangoproject.com/ja/2.2/
https://docs.djangoproject.com/ko/2.2/
https://docs.djangoproject.com/pl/2.2/
https://docs.djangoproject.com/pt-br/2.2/
https://docs.djangoproject.com/zh-hans/2.2/
https://docs.djangoproject.com/en/1.7/
https://docs.djangoproject.com/en/1.8/
https://docs.djangoproject.com/en/1.9/
https://docs.djangoproject.com/en/1.10/
https://docs.djangoproject.com/en/1.11/
https://docs.djangoproject.com/en/2.0/
https://docs.djangoproject.com/en/2.1/
https://docs.djangoproject.com/en/dev/